### ISSUE TITLE
add auto attack with mushrooms

### ISSUE THREAD

**Issue by asdlolasd12** [the-marenga/sf-scrapbook-helper#17]
hello can you please add a choice to album farming with mushrooms ? it will helps alot

**Comment by asdlolasd12** [comment]
> hello can you please add a choice to album farming with mushrooms ? it will helps alot

(auto fight with shrooms)

**Comment by the-marenga** [comment]
I don't think I am going to add this any time soon. There is just no real usecase, since you could just spam the first entry for a minute, if you want to spend mushrooms and there is just too much risk, if someone accidentally enables this and the tool wastes 10$ worth of mushrooms in an instance. If anyone has other arguments, feel free to reopen this, but for the time being this will not be implemented
