### ISSUE TITLE
Issue with Windows 11 (Windows 10 is fine)

### ISSUE THREAD

**Issue by DasAoD** [the-marenga/sf-scrapbook-helper#3]
First of all, a big thanks for this program.

Srapbook Helper runs fine under Windows 10.
Login via SSO (S&F account), as well as via the normal login (character name + password), works.
Manual and automatic attacks also work without any problems.
![Scrapbook Helper Windows 10](https://github.com/the-marenga/sf-scrapbook-helper/assets/42589682/85b79539-fd17-4b48-9af9-3b0392f704ee)

Unfortunately, I can't get Scrapbook Helper working under Windows 11.
Even with deactivated real-time protection of the Defender and with various compatibility modes, the program would not start.
![Scarpbook Helper Windows 11](https://github.com/the-marenga/sf-scrapbook-helper/assets/42589682/6b09ab6e-c2b4-4001-9289-7d6e875c9916)

The window remains empty and shortly afterwards the program hangs.

Update:
I was able to start the program on another Windows 11 PC without any problems.

**Comment by DasAoD** [comment]
I've now tried to save the .exe in different locations, which always resulted in the same error.
However, as soon as I copy the .exe to the desktop or create a shortcut there, I can start the program without any problems, regardless of where I have saved the .exe.
Very strange. :D

**Comment by the-marenga** [comment]
Hm... very strange indeed. If the location of the executable matters, this sounds more like an anti-virus, or privilege settings issue. I tried to replicate it with the same windows build version, but for me it just always works, regardles of the location, or security settings. Even the typically roblematic Programfiles folder and network drives work flawlessly...

Regardless, I tried to just change a few things, that might have an influence on the issue. If you want, you can try to run these and tell me, what you see:

[test.zip](https://github.com/the-marenga/sf-scrapbook-helper/files/13883342/test.zip)

Otherwise I would just add a disclaimer in case anyone runs into the same issue, if you can otherwise just the program fine from the desktop/shortcut.

Oh, and thanks for following up on the issue: 😄

**Comment by DasAoD** [comment]
I tested all 4 .exe files from the test.zip on my system.
In my case, the sf-scrapbook-helper-db.exe was the only one that I could start without any problems, regardless of where I saved it.

I am assuming that it is simply due to my user profile, although I reinstalled the entire system about 6 weeks ago.
Even the shortcut on the desktop doesn't start right away from time to time.
On my wife's Windwos 11 system (same build), I can start the program from anywhere without any restrictions.

Only Microsoft Defender is active on both systems. No other third-party programs.

A disclaimer would certainly be an advantage.

No problem. I want to help as much as I can. Besides, I also benefit from the program ;)

**Comment by the-marenga** [comment]
If only the "-db" version works, that means it is an issue with the GUI library I used and I can not fully fix it myself. For some reason, hiding the terminal window, that opens at launch, just does not seem to work on your machine. 

Guess I am going to add a disclaimer
