### ISSUE TITLE
[Bug] Windows defender reporting virus

### ISSUE THREAD

**Issue by TassioS** [the-marenga/sf-scrapbook-helper#31]
Hello I can't execute the new version 0.2.0 file because windows is blocking saiyng it found a Trojan:Win32/Wacatac.B!ml. 

previous one was ok

**Comment by the-marenga** [comment]
That is annoying, but thanks for the info. On my machine and virustotal, microsoft has no problem with the file. 

Might be some dynamic analysis, that triggers, because the program now connects to github and shakes and fidget on startup, instead of after a few seconds have passed and also creates two files immediately. I might need to change that for the next release then. Should probably also fix the auto-build pipeline. Programs build by github might be ranked safer, then when I compile and upload the program from my machine

**Comment by the-marenga** [comment]
I just updated the release version to be automatically build by github again. Feel free to try that version and see, if it is still reported. Otherwise I might just have to rewrite all the connection stuff to happen later or something

**Comment by adriamt** [comment]
Same here
