### ISSUE TITLE
[Bug] Multiple SSO accounts running on same server keeps logging out

### ISSUE THREAD

**Issue by PavelV99** [the-marenga/sf-scrapbook-helper#49]
After 3-4 fights (sometimes longer) second account is stacked at Logging in. Only solution right now is to restart the Scrapbook Helper and add account again.

**Comment by the-marenga** [comment]
Hmmm... sso accounts need to sync their auth together, which likely causes these problems. I thougth I made sure that was all fine, but I guess I missed something. 

Are you interacting with S&F through another way, whilst this is happening (Webbrowser/Steam/Android/MFBot), or is this just happening by itself? 

Might also help, if you share your helper.log file. That might contain warnings, that point me in the right direction.

**Comment by the-marenga** [comment]
Thanks for the info!

```
Update ignored success" -> ResponseVal { value: "false,"status":401,"data":{"error":"access_denied","error_description":"The resource owner or authorization server denied the request.","hint":"Access token could not be verified","message":"The resource owner or authorization server denied the request."}}", sub_key: "" }
```

That means the sever sends back a "success", which means everything went as expected and then in the extra info, it states, that there is actually an error... I love working with the S&F servers, you can not trust them ever it seems...

Anyway, that means I will have to make sure "success" does not contain an error I guess and make sure to handle that error. Might take a bit of time though, but should be fixed in the next release

**Comment by the-marenga** [comment]
I am going to assume, that some of the previous fixes resolved this issue. Feel free to reopen this, if you still have this issue
