### ISSUE TITLE
[Feature Request] Min. Level

### ISSUE THREAD

**Issue by JustYuura** [the-marenga/sf-scrapbook-helper#56]
I'm unsure if it would speed up the total fetching/scanning process significantly; if it did adding a Minimum Level selector next to the maximum level one would make the experience better as soon as you're done with most items and/or are, mostly on newer servers, looking for items in a specific level range.

**Comment by the-marenga** [comment]
Thanks for the suggestion. 

The existing max Level has no effect on the crawling speed. It only acts as a filter on the list of already crawled characters. I implemented it like this, because that makes it easier to share hall of Fame data across accounts. 

In theory making additional max/min Limits on the actual crawling process could speed up crawling by up to 50x for hall of Fame regions, that would get completely skipped. So far, the best way would be to just select the crawling order "top down" to start with the high level accounts, which has a similar effect. 

This is however the second time someone requested something like this, so I guess this is important. Implementing this should also be easy, but I will have to think about how to make this understandable in the ui to make sure nobody Limits crawling on one account and then wonders, why a second account on the same server finds nothing. 

If I had to guess, I will add an "advanced crawling options" checkbox or something in the settings to hide these options behind. Should be coming in the next release, once I am back from holidays (~2 weeks)
