### ISSUE TITLE
Input fields accept no direct numeric input

### ISSUE THREAD

**Issue by JustYuura** [the-marenga/sf-scrapbook-helper#67]
The input fields Max Level/Threads/Min Level and so on do not accept any direct numeric input. This has been around for a while though it has never really been too much of a bother since the only thing you're usually changing is the number of threads used for crawling but this has changed with the introduction of the Min Level advanced option.
Pressing the little up-arrow potentially way upwards of a hundred times is not really ergonomic and makes that feature borderline unusable.

**Comment by the-marenga** [comment]
Thanks for the report.

So the problem is, that they always worked for me, so I never noticed this.

I think I found the underlying issue though and I would like you to confirm this. **Does your number input work, if you have your mouse over the input numbers?** 

I always keep my mouse there anyways, so I never noticed this, but it seems like these fields require the mouse cursor to be over the numbers for unknown reasons. If this is the issue, then this is probably not actually my bug, but a but in the UI library I use and not something I can easily fix in them.

The best solution would probably be to just use a normal text input (like the ones on the login pages) then, as they do not seem to have this issue. That would mean losing the arrows, but they would at least work reliably

**Comment by the-marenga** [comment]
Thanks for testing. I will file a bug with the UI library then and switch to a regular text input, until this is fixed upstream
