### ISSUE TITLE
HOF sharing (suggestion)

### ISSUE THREAD

**Issue by Jirkaon** [the-marenga/sf-scrapbook-helper#9]
Hello,
it isn’t an issue, but more like question or suggestion. It would be nice to create a function or some shared cloud, when people can share their crawled HOF so others don’t have to. It would be quicker, especially if you need to crawl a fusion server which can take hours by itself, and beneficial so people don’t create lots of dummy accounts.

**Comment by the-marenga** [comment]
Yeah, that would in fact be amazing and I thought about that, but the problem becomes, that this becomes a legal headache, that I try to stay away from for the moment. When I did crawling of websites at my university, we had to consult our legal department and the main points were:
- You are not allowed to crawl data as a whole and distribute that, even for free, or research. Only some percentage
- Given that this is to some extend user created data, I need to provide a way for people to be removed from the dataset (Recht auf Vergessen)
- When I presumably host this crawled data on my own servers, I am to some extend hosting data/knowledge owned/controled by playa games, which would give them at least a some legal justification to send me a cease and desist letter, which I would really like to not receive
- The servers for the game are hosted in different countries with different regulation. Storing all of them in one location could be problematic, given that EU user data has some issues being exported outside and that might be true for other places.

There are some ways to make this less bad, namely:
- Remove all duplicate (same or less equipment and higher level) characters from the dataset to get below the crawling threshold.
- Have my email somewhere for people to write to when they want to be removed and hope that never happens

Currently I am studying for my German-IT-law exam, so I just see possible issues everywhere. In practice I dont think anybody actually cares about a few json files with usernames and a few numbers hosted somewhere, but for the time being I don't want to take the chance, especially, since "a friend of mine" has already been banned from github for uploading crawled data, so I will try to stay away from that stuff for now... 

Anyways, if you, or anyone else that reads this issue has more experience, or knowledge about this sort of legal EU stuff and can provide me with something to change my understanding, feel free to let me know. It is very possible, that I overlooked or misinterpreted something

**Comment by the-marenga** [comment]
Alternatively it might be possible to crawl the data and have it hidden on a server, that only provides an API to query the best players to attack, given an input scrapbook. I think there would be less issues, but at that point
- I would see which players use this tool
- I would still run into some of the issues listed above

**Comment by the-marenga** [comment]
Of course, if you or anyone else creates a shared GDrive, or OneDrive folder and spreads that in the community on their own, that is fine by me. I just can't promote/share that here, or in the tool itself I think

**Comment by Jirkaon** [comment]
Oh, okay. You had totally different opinion on the topic. I didn’t think about it like that, but can only agree with you. I see your point. Maybe I will try some distribution on my own so you have nothing to do with it.
