### ISSUE TITLE
[Feature Request] ''Editable'' number colomuns

### ISSUE THREAD

**Issue by Jirkaon** [the-marenga/sf-scrapbook-helper#99]
Hello,
I have an idea that could be helpful. It is really tedious if you want to increase your opponent level for example by 100 lvl to do it by clicking on the arrow up or down. Would be nice to just click in the numbers field and type the number i want. Or hold the arrow and it would change the lvl automatically. The same principle would be applicable to the Max Attributes field.

**Comment by the-marenga** [comment]
You mean the max level field? You should already be able to just write a number into that

**Comment by Jirkaon** [comment]
Yes, that is what I meant. Sorry I did not cought it earlier, because on my main PC it did not work. So I tried now another PC and it worked, but it is somehow broken. The numbers are somehow overwriting. If you want to type for example 12345 it writes 1234 and than changes the 4 for 5 so the number looks like 1235. It did for me for multiple number lenghts. Both PCs are on the last version 0.2.5. After redownloading on my main PC, it started working but is broken in the same way.

**Comment by the-marenga** [comment]
Thanks for the extensive testing! That number input is a bit of a headache for me. It is not my code, it is from a library called iced-aw, but I already had to fix another bug there, so I am somewhat familiar with the code. If I recall correctly, they manually reimplement a bunch of text input & parsing and the bug you are describing sounds exactly like a bug, that would happen with manually handling cursor movements, or clipping the input string. 

As long as this only happens for large numbers (greater, than any level you would normaly input) and the not working entirely part only happened once on one of your pcs, I would just keep this as is. At some point, this will just be fixed in the library and than that fix will be applied to this project here via a dependency update. 

If this is a large issue for you, you can reopen this, but I would just wait for this to fix itself
